### ISSUE TITLE
Stale repository, adding reference to aswf-docker?

### ISSUE THREAD

**Issue by grische** [mottosso/vfxplatform-docker#1]
@fredrikaverpil @mottosso as this repository here is still #1 Google search hit, would you consider adding the ASWF repository for vfxplatform docker containers to your README.md?

https://github.com/AcademySoftwareFoundation/aswf-docker

**Comment by mottosso** [comment]
Sure, if you put together a PR with the changes you'd like to see I'll merge asap.

**Comment by grische** [comment]
@mottosso in case the notification went missing, I created a PR.

**Comment by mottosso** [comment]
Thanks, it had. :)
